language: csharp
mono: none
dotnet: 2.1.502
solution: "./Coveralls.sln"
script:
 - dotnet restore --packages ./packages
 - ls ./packages/coveralls.net/0.7.0/tools
 - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover ./Coveralls-Net-Standard.Tests/Coveralls-Net-Standard.Tests.csproj
 - ls ./Coveralls-Net-Standard.Tests
 - chmod +x ./packages/coveralls.net/0.7.0/tools/csmacnz.Coveralls.exe
 - ./packages/coveralls.net/0.7.0/tools/csmacnz.Coveralls.exe --opencover -i ./Coveralls-Net-Standard.Tests/coverage.opencover.xml --useRelativePaths