language: csharp
mono: none
dotnet: 2.1.502
solution: "./Coveralls.sln"
script:
 - dotnet restore --packages ./packages
 - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover ./Coveralls-Net-Standard.Tests/Coveralls-Net-Standard.Tests.csproj
 - ls ./Coveralls-Net-Standard.Tests
 - dotnet tool install coveralls.net --version 1.0.0 --tool-path packages
 - ./packages/csmacnz.Coveralls --opencover -i ./Coveralls-Net-Standard.Tests/coverage.opencover.xml --useRelativePaths